Water Pollution Dataset Analysis

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_excel("water_pollution_dataset.xlsx")

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index'],
      dtype='str')

In [ ]:
df['Country']

0            USA
1            USA
2          India
3          India
4          China
          ...
18255      China
18256     Brazil
18257     Brazil
18258    Germany
18259    Germany
Name: Country, Length: 18260, dtype: str

In [ ]:
# Q1. For each city, determine the typical acidity level of the water.Which city has the most acidic water on average?                   # acidic level ka koi bhi column nahi hai toh  mai ph value ka sue kiya column ka 

avg_ph = df.groupby('City').agg({'pH Level': 'mean'})   # City ke according data group karke har city ka average pH nikal rahe hain

print(avg_ph)   # Har city ka average pH screen par dekh rahe hain

lowest = avg_ph['pH Level'].min()   # Sabhi cities ke average pH mein se sabse lowest pH value nikal rahe hain

print(avg_ph[avg_ph['pH Level'] == lowest])   # Jis city ka average pH sabse lowest hai, us city ko print kar rahe hain

                pH Level
City
Beijing         6.991134
Berlin          6.991807
Delhi           7.007245
Los Angeles     6.990438
Mumbai          6.999392
Munich          7.003028
New York        6.993949
Rio de Janeiro  6.999085
Shanghai        7.005077
São Paulo       7.008828
             pH Level
City
Los Angeles  6.990438

In [ ]:
# 2 In the USA, examine the overall dissolved oxygen levels in water sources. What are the typical values across all records?

oxygen = df.loc[df['Country'] == 'USA']['Dissolved Oxygen (mg/L)'].mean()  # USA ke records ko filter karke Dissolved Oxygen ka average nikal raha hu

print(oxygen)

6.003891018619935

In [ ]:
df['City']

0              New York
1           Los Angeles
2                Mumbai
3                 Delhi
4               Beijing
              ...
18255          Shanghai
18256    Rio de Janeiro
18257         São Paulo
18258            Berlin
18259            Munich
Name: City, Length: 18260, dtype: str

In [ ]:
# 3 Focus on data from Brazil. Which city experiences the highest pollution levels over the 5-year period?

# Brazil ke records ko filter karke City aur Pollution Index columns select kar rahe hain
df_3 = df.loc[df['Country'] == 'Brazil'][['City', 'Pollution Index']]

# Pollution Index ko highest se lowest order mein arrange kar rahe hain
df_3 = df_3.sort_values(by='Pollution Index', ascending=False).head(5)

# Sabse highest pollution wali city ka result print kar rahe hain
print(df_3)

                 City  Pollution Index
12826  Rio de Janeiro        64.989079
13226  Rio de Janeiro        64.961648
5376   Rio de Janeiro        64.955681
2236   Rio de Janeiro        64.914180
13037       São Paulo        64.907940

In [ ]:
df['City']

0              New York
1           Los Angeles
2                Mumbai
3                 Delhi
4               Beijing
              ...
18255          Shanghai
18256    Rio de Janeiro
18257         São Paulo
18258            Berlin
18259            Munich
Name: City, Length: 18260, dtype: str

In [ ]:
# 4 In Mumbai, identify the date when water pollution was at its worst.

# Filter Mumbai, sort pollution from highest to lowest,
# select the first row, and return its date.

df.loc[df['City'] == 'Mumbai'].sort_values(by='Pollution Index', ascending=False).iloc[0]['Date']

Timestamp('2019-08-06 00:00:00')

In [ ]:
# 5 For each country, determine how many pollution records were collected. Which country has the most entries?

df.groupby('Country').agg({'Pollution Index' : 'count'}).sort_values(by = 'Pollution Index', ascending = False)

# Har country ke pollution records count kara hu 
# Pollution Index ke count ko highest se lowest sort kara hu 
# Sabse zyada entries wali country sabse upar aayegi

         Pollution Index
Country
Brazil              3652
China               3652
Germany             3652
India               3652
USA                 3652

In [ ]:
# 6 Compare the average water quality for rivers versus lakes in terms of biological oxygen demand. Which type of water source has more organic matter?

# Sirf River aur Lake ka data select karo
# Water Source ke basis par groups banao
# Har group ka average Biological Oxygen Demand (BOD) nikaalo

df[df['Water Source'].isin(['River', 'Lake'])].groupby('Water Source').agg({'Biological Oxygen Demand (BOD)': 'mean'})   # isin ka matlb  agar wateersourse mai hai river or alke tab unka group kr do

              Biological Oxygen Demand (BOD)
Water Source
Lake                               10.732219
River                              10.676696

In [ ]:
# 7 Examine how pollution levels have changed in different countries over the years. Which country has seen the largest increase in pollution?

# Date ko purane se naye order mein sort karo
# Har country ka first aur last Pollution Index nikalo
# Pollution increase calculate karke highest increase find karo


df_7 = df.sort_values('Date').groupby('Country').agg(  # Date sort karke country-wise group banao
    first=('Pollution Index', 'first'),  # Har country ka pehla Pollution Index nikalo
    last=('Pollution Index', 'last')     # Har country ka aakhri Pollution Index nikalo
)

df_7['Increase'] = df_7['last'] - df_7['first']  # Last aur first ka difference nikalo

df_7.sort_values('Increase', ascending=False).head(1)  # Sabse zyada increase wali country dikhao

             first       last   Increase
Country
Germany  21.550508  40.542227  18.991719

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index'],
      dtype='str')

In [ ]:
# 8 Investigate nitrate levels across various water sources in different countries. How do they compare?

df_8 = df.groupby(['Country', 'Water Source']).agg({'Nitrates (mg/L)': 'mean'}).sort_values('Nitrates (mg/L)', ascending=False)  # Country + source ka average nitrate, highest upar

print(df_8)

                      Nitrates (mg/L)
Country Water Source
India   Canal                6.968184
        Lake                 6.959249
China   River                6.905056
        Canal                6.877696
        Lake                 6.865778
        Bay                  6.862271
India   River                6.802425
        Bay                  6.783774
Brazil  River                6.048418
        Lake                 5.990766
        Canal                5.951208
        Bay                  5.814862
Germany River                5.104550
USA     River                5.091398
        Lake                 5.086608
        Canal                5.037930
Germany Canal                5.009169
        Lake                 4.994814
        Bay                  4.889142
USA     Bay                  4.877171

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index'],
      dtype='str')

In [ ]:
# 9 For New York, track how water pollution has changed over time. Is there a noticeable trend over the 5-year period?

df.loc[df['City'] == 'New York'].groupby('Date').agg({'Pollution Index': 'mean'}).reset_index() # New York ka date-wise average pollution trend

           Date  Pollution Index
0    2019-01-01        23.266387
1    2019-01-02        24.992785
2    2019-01-03        36.003913
3    2019-01-04        26.577520
4    2019-01-05        37.043400
...         ...              ...
1821 2023-12-27        22.572338
1822 2023-12-28        28.660027
1823 2023-12-29        24.648370
1824 2023-12-30        25.057299
1825 2023-12-31        24.053370

[1826 rows x 2 columns]

In [ ]:
# 10 Look at how pollution levels change throughout the year in each city. Which cities experience the most significant seasonal variations?

df['Month'] = pd.to_datetime(df['Date']).dt.month  # Date se Month nikala

df.groupby(['City', 'Month']).agg({'Pollution Index': 'mean'}).reset_index()  # Har city ke har month ka average pollution

          City  Month  Pollution Index
0      Beijing      1        59.525278
1      Beijing      2        59.864065
2      Beijing      3        60.062770
3      Beijing      4        60.556099
4      Beijing      5        60.292695
..         ...    ...              ...
115  São Paulo      8        54.759675
116  São Paulo      9        44.376818
117  São Paulo     10        45.330427
118  São Paulo     11        45.442757
119  São Paulo     12        44.473687

[120 rows x 3 columns]

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index', 'Month'],
      dtype='str')

In [ ]:
# 11 Examine the relationship between pollution and various water quality parameters like dissolved oxygen, biological oxygen demand, and nitrates. Which parameter seems to be most closely linked with pollution levels?

df_11 = df.groupby('Pollution Index').agg({'Dissolved Oxygen (mg/L)' : 'mean','Biological Oxygen Demand (BOD)' : 'mean','Nitrates (mg/L)' : 'mean'})  # Pollution Index ke according teeno water quality parameters ka mean

print(df_11)

                 Dissolved Oxygen (mg/L)  Biological Oxygen Demand (BOD)  \
Pollution Index
20.005800                           8.00                            5.37
20.018796                           8.00                            6.57
20.019229                           8.00                            9.46
20.019709                           8.00                            4.48
20.024281                           8.00                            4.51
...                                  ...                             ...
79.816947                           2.02                           12.05
79.823144                           2.02                           16.66
79.834597                           2.02                           11.66
79.896900                           2.01                           10.61
79.962406                           2.00                           13.36

                 Nitrates (mg/L)
Pollution Index
20.005800                   2.54
20.018796                   1.55
20.019229                   2.65
20.019709                   2.90
20.024281                   3.49
...                          ...
79.816947                  14.45
79.823144                   8.66
79.834597                  14.13
79.896900                  15.44
79.962406                  11.71

[18260 rows x 3 columns]

In [ ]:
# 12 Track pollution trends over time for multiple cities. Which cities have improved or worsened over the 5 years?

df['Year'] = pd.to_datetime(df['Date']).dt.year  # Date se Year nikala

df_12 = df.groupby(['City', 'Year']).agg({'Pollution Index': 'mean'}).reset_index()  # Har city aur year ka average pollution nikala

print(df_12)

              City  Year  Pollution Index
0          Beijing  2019        62.059290
1          Beijing  2020        62.716791
2          Beijing  2021        63.198252
3          Beijing  2022        62.638794
4          Beijing  2023        62.319248
5           Berlin  2019        32.343431
6           Berlin  2020        32.409889
7           Berlin  2021        32.617392
8           Berlin  2022        32.443403
9           Berlin  2023        32.028477
10           Delhi  2019        47.689459
11           Delhi  2020        47.337975
12           Delhi  2021        47.425685
13           Delhi  2022        47.550347
14           Delhi  2023        47.320152
15     Los Angeles  2019        47.251767
16     Los Angeles  2020        47.718006
17     Los Angeles  2021        47.047728
18     Los Angeles  2022        48.052750
19     Los Angeles  2023        47.670025
20          Mumbai  2019        62.462546
21          Mumbai  2020        62.035223
22          Mumbai  2021        62.375849
23          Mumbai  2022        63.098333
24          Mumbai  2023        62.337749
25          Munich  2019        48.157687
26          Munich  2020        47.439050
27          Munich  2021        47.636896
28          Munich  2022        47.349990
29          Munich  2023        47.604849
30        New York  2019        31.867502
31        New York  2020        32.363719
32        New York  2021        32.073578
33        New York  2022        33.272348
34        New York  2023        32.285592
35  Rio de Janeiro  2019        47.718256
36  Rio de Janeiro  2020        47.889412
37  Rio de Janeiro  2021        48.455162
38  Rio de Janeiro  2022        47.458615
39  Rio de Janeiro  2023        47.649720
40        Shanghai  2019        47.682198
41        Shanghai  2020        47.688458
42        Shanghai  2021        47.644327
43        Shanghai  2022        47.319296
44        Shanghai  2023        47.308552
45       São Paulo  2019        46.883327
46       São Paulo  2020        47.823351
47       São Paulo  2021        47.752709
48       São Paulo  2022        47.957038
49       São Paulo  2023        47.406279

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index', 'Month', 'Year'],
      dtype='str')

In [ ]:
# 13 Identify any unusual or extreme values for the pH level in each city. On which days did water acidity or alkalinity differ the most from typical values?

city_avg = df.groupby('City').agg({'pH Level': 'mean'}).reset_index()

# City ke basis par INNER JOIN
df = df.merge(city_avg, on='City', how='inner', suffixes=('', '_avg'))

# Actual pH aur average pH ka difference
df['Difference'] = (df['pH Level'] - df['pH Level_avg']) ** 2

# Sabse bada difference upar
df = df.sort_values('Difference', ascending=False)

# Har city ka extreme record
result = df.groupby('City').head(1)

print(result[['City', 'Date', 'pH Level', 'pH Level_avg', 'Difference']])

                 City       Date  pH Level  pH Level_avg  Difference
12321     Los Angeles 2022-05-17       7.5      6.990438    0.259653
6214          Beijing 2020-09-13       7.5      6.991134    0.258945
11147       São Paulo 2022-01-19       6.5      7.008828    0.258906
9168           Berlin 2021-07-05       7.5      6.991807    0.258260
9453            Delhi 2021-08-03       6.5      7.007245    0.257298
6250         New York 2020-09-17       7.5      6.993949    0.256088
7035         Shanghai 2020-12-04       6.5      7.005077    0.255102
2029           Munich 2019-07-22       6.5      7.003028    0.253038
1016   Rio de Janeiro 2019-04-12       7.5      6.999085    0.250915
3232           Mumbai 2019-11-20       7.5      6.999392    0.250608

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index', 'Month', 'Year',
       'pH Level_avg', 'Difference'],
      dtype='str')

In [ ]:
# 14 For each country and water source, find out which combinations have the worst pollution levels.

df.groupby([ 'Country','Water Source']).agg({'Pollution Index': 'mean'}).sort_values(by = 'Pollution Index',ascending= False).head(1)  # Country + Water Source group → Max pollution → Sort → Worst combination

                      Pollution Index
Country Water Source
China   Canal               55.437389

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index', 'Month', 'Year',
       'pH Level_avg', 'Difference'],
      dtype='str')

In [ ]:
# 15 Investigate how heavy metal contamination (Lead and Mercury) has changed over the 5-year period. Are any cities seeing an increase or decrease in contamination?

# City aur Year ke hisaab se Lead aur Mercury ka average
df_15 = df.groupby(['City','Year']).agg({'Lead (mg/L)': 'mean','Mercury (mg/L)': 'mean'}).reset_index()

# City aur Year ko order mein laga rahe hain
df_15 = df_15.sort_values(by=['City','Year'])

# Har city ki first aur last year ki value nikal rahe hain
df_15 = df_15.groupby('City').agg({'Lead (mg/L)': ['first','last'],'Mercury (mg/L)': ['first','last']})

print(df_15)

               Lead (mg/L)           Mercury (mg/L)
                     first      last          first      last
City
Beijing           0.033822  0.033992       0.003462  0.003413
Berlin            0.017625  0.016953       0.001785  0.001801
Delhi             0.025482  0.026030       0.002592  0.002597
Los Angeles       0.026849  0.026247       0.002651  0.002632
Mumbai            0.034992  0.034353       0.003422  0.003510
Munich            0.027060  0.024532       0.002667  0.002579
New York          0.016800  0.017490       0.001733  0.001767
Rio de Janeiro    0.026205  0.026767       0.002588  0.002575
Shanghai          0.026159  0.025474       0.002661  0.002626
São Paulo         0.025638  0.025559       0.002631  0.002615

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index', 'Month', 'Year',
       'pH Level_avg', 'Difference'],
      dtype='str')

In [ ]:
# 16 Assign each record to a pollution severity category based on overall pollution levels. How do cities compare in terms of the proportion of records in the highest severity category?

df['Severity'] = np.where(df['Pollution Index'] > 70, 'High', np.where(df['Pollution Index'] > 40, 'Medium', 'Low'))  # Pollution ko High, Medium, Low mein divide kiya

df_16 = df.groupby(['City', 'Severity']).agg({'Pollution Index': 'mean'}).reset_index()  # Har city mein har severity ke records count kiye

print(df_16) 

# Insight: Beijing aur Mumbai mein pollution severity sabse high hai, jinka average Pollution Index 74.85 aur 74.75 hai.

              City Severity  Pollution Index
0          Beijing     High        74.849715
1          Beijing   Medium        60.801693
2           Berlin      Low        30.673324
3           Berlin   Medium        45.206028
4            Delhi      Low        37.567396
5            Delhi   Medium        49.745559
6      Los Angeles      Low        37.539735
7      Los Angeles   Medium        49.805079
8           Mumbai     High        74.749305
9           Mumbai   Medium        60.611211
10          Munich      Low        37.492224
11          Munich   Medium        49.984085
12        New York      Low        30.580510
13        New York   Medium        44.564491
14  Rio de Janeiro      Low        37.596220
15  Rio de Janeiro   Medium        50.026185
16        Shanghai      Low        37.529230
17        Shanghai   Medium        49.685653
18       São Paulo      Low        37.524538
19       São Paulo   Medium        49.928668

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index', 'Month', 'Year',
       'pH Level_avg', 'Difference', 'Severity'],
      dtype='str')

In [ ]:
# 17 Look at the seasonal patterns of pollution for each city. Are there specific times of year when pollution tends to rise or fall?# 17 Look at the seasonal patterns of pollution for each city. Are there specific times of year when pollution tends to rise or fall?

df['Month'] = pd.to_datetime(df['Date']).dt.month  # Date se Month nikala

df_17 = df.groupby(['City','Month']).agg({'Pollution Index':'mean'}).reset_index()  # City aur Month ka average pollution

df_17 = df_17.sort_values(by=['City','Month'], ascending=True)  # City aur Month ko ascending order mein sort kiya

df_17['Rise_Fall'] = np.where(df_17['Pollution Index'] > 50, 'Rise', 'Fall')  # 50 se zyada = Rise, warna Fall

print(df_17)

          City  Month  Pollution Index Rise_Fall
0      Beijing      1        59.525278      Rise
1      Beijing      2        59.864065      Rise
2      Beijing      3        60.062770      Rise
3      Beijing      4        60.556099      Rise
4      Beijing      5        60.292695      Rise
..         ...    ...              ...       ...
115  São Paulo      8        54.759675      Rise
116  São Paulo      9        44.376818      Fall
117  São Paulo     10        45.330427      Fall
118  São Paulo     11        45.442757      Fall
119  São Paulo     12        44.473687      Fall

[120 rows x 4 columns]

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index', 'Month', 'Year',
       'pH Level_avg', 'Difference', 'Severity'],
      dtype='str')

In [ ]:
# 18 Create a risk index based on a combination of biological oxygen demand, chemical oxygen demand, and nitrates. Which city is most at risk based on this index?

df['Risk_index'] = df['Biological Oxygen Demand (BOD)'] + df['Chemical Oxygen Demand (COD)'] + df['Nitrates (mg/L)']  # BOD + COD + Nitrates ko add karke Risk Index banaya

df_18 = df.groupby('City').agg({'Risk_index': 'mean'})  # Har city ka average Risk Index nikala

print(df_18)  

# Beijing → 44.98  =  sabse highest Risk Index

                Risk_index
City
Beijing          44.983746
Berlin           31.736889
Delhi            38.267853
Los Angeles      38.022536
Mumbai           44.196172
Munich           37.884009
New York         31.520361
Rio de Janeiro   38.461714
Shanghai         38.022360
São Paulo        38.096117

In [ ]:
df.columns

Index(['Date', 'Country', 'City', 'Water Source', 'pH Level',
       'Dissolved Oxygen (mg/L)', 'Biological Oxygen Demand (BOD)',
       'Chemical Oxygen Demand (COD)', 'Nitrates (mg/L)', 'Phosphates (mg/L)',
       'Lead (mg/L)', 'Mercury (mg/L)', 'Pollution Index', 'Month', 'Year',
       'pH Level_avg', 'Difference', 'Severity', 'Risk_index'],
      dtype='str')

In [ ]:
# 19 Predict future pollution levels for one city based on past data. What could the pollution level be next year?

df['Year'] = pd.to_datetime(df['Date']).dt.year  # Date se Year nikala

df_19 = df[df['City'] == 'Mumbai'].groupby('Year').agg({'Pollution Index': 'mean'}).reset_index()  # Mumbai ka year-wise average pollution

print(df_19)

   Year  Pollution Index
0  2019        62.462546
1  2020        62.035223
2  2021        62.375849
3  2022        63.098333
4  2023        62.337749