In [15]:
#Import library

import pandas as pd 
import numpy as np

In [16]:
#Load Dataset 

df=pd.read_excel("Hospital_Patient_Dataset.xlsx")

In [17]:
#Top 5 Records 

df.head()

   PatientName   Attribute       Value
0  Aarav Joshi         Age          32
1  Aarav Joshi      Gender        Male
2  Aarav Joshi  BloodGroup         AB+
3  Aarav Joshi        City     Chennai
4  Aarav Joshi       State  Tamil Nadu

In [18]:
# bottom 5 Records

df.tail()

         PatientName        Attribute      Value
1048570  Lata Mishra  DiscountPercent         10
1048571  Lata Mishra        FinalBill  119298.41
1048572    Neha Iyer              Age         58
1048573    Neha Iyer           Gender     Female
1048574    Neha Iyer       BloodGroup         B-

In [19]:
#Dataset Shape 
df.shape

(1048575, 3)

In [20]:
#Column Names 
df.columns

Index(['PatientName', 'Attribute', 'Value'], dtype='str')

In [21]:
#Dataset Information 

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PatientName  1048575 non-null  str
 1   Attribute    1048575 non-null  str
 2   Value        1048575 non-null  object
dtypes: object(1), str(2)
memory usage: 24.0+ MB

In [22]:
#missing values 
df.isnull().sum()

PatientName    0
Attribute      0
Value          0
dtype: int64

In [23]:
#Total Missing Values

df.isnull().sum().sum()

np.int64(0)

In [24]:
#10.duplicate Rows 
df.duplicated().sum()

np.int64(651212)

In [25]:
#Remove Duplicate
df= df.drop_duplicates()

In [26]:
#CheckAgain 
df= df.duplicated().sum()