In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("all_neet_marks_2607.csv")

In [3]:
# 1. How many students are present in the dataset
df.shape[0]

2333162

In [4]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [5]:
# 2. How many states are present
df["state"].nunique()

38

In [45]:
sum(df['Marks'])

506661495

In [46]:
df['Marks'].sum()

np.int64(506661495)

In [48]:
df['Marks'].max()

np.int64(720)

In [49]:
df['Marks'].min()

np.int64(-180)

In [6]:
df["city"].nunique()  # tota number of uniwue value batata hai

567

In [ ]:
df.groupby('state').agg({'Marks':'sum'})

                                     Marks
state
ANDAMAN AND NICOBAR ISLANDS (UT)    197556
ANDHRA PRADESH                    16661956
ARUNACHAL PRADESH                   777670
ASSAM                              8453395
BIHAR                             25683883
CHANDIGARH(UT)                     1076003
CHHATTISGARH                       8212726
DADRA AND NAGAR HAVELI (UT)         267872
DAMAN AND DIU (UT)                  138604
DELHI                             16928057
GOA                                 969592
GUJARAT                           21315275
HARYANA                           14338696
HIMACHAL PRADESH                   4302471
JAMMU AND KASHMIR                  9768028
JHARKHAND                          7153017
KARNATAKA                         33116704
KERALA                            32655149
LADAKH(UT)                          119037
LAKSHADWEEP (UT)                     25070
MADHYA PRADESH                    22695925
MAHARASHTRA                       55676862
MANIPUR                            1790773
MEGHALAYA                           587630
MIZORAM                             398553
NAGALAND                            640197
ODISHA                            13161367
OUTSIDE-INDIA                      1191185
PUDUCHERRY(UT)                     1140100
PUNJAB                             6076245
RAJASTHAN                         54144868
SIKKIM                              258971
TAMIL NADU                        33868938
TELANGANA                         17351045
TRIPURA                             908338
UTTAR PRADESH                     64103327
UTTARAKHAND                        4756524
WEST BENGAL                       25749886

In [55]:
df.groupby('state').agg({'Marks':'mean'})

                                       Marks
state
ANDAMAN AND NICOBAR ISLANDS (UT)  192.737561
ANDHRA PRADESH                    260.971024
ARUNACHAL PRADESH                 162.896942
ASSAM                             190.937931
BIHAR                             188.584457
CHANDIGARH(UT)                    304.816714
CHHATTISGARH                      185.636084
DADRA AND NAGAR HAVELI (UT)       221.932063
DAMAN AND DIU (UT)                180.239272
DELHI                             256.136435
GOA                               196.671805
GUJARAT                           245.138410
HARYANA                           261.349810
HIMACHAL PRADESH                  225.685638
JAMMU AND KASHMIR                 205.413497
JHARKHAND                         207.912365
KARNATAKA                         219.465622
KERALA                            235.698966
LADAKH(UT)                        166.485315
LAKSHADWEEP (UT)                  150.119760
MADHYA PRADESH                    174.264999
MAHARASHTRA                       202.281102
MANIPUR                           200.175833
MEGHALAYA                         156.409369
MIZORAM                           155.139354
NAGALAND                          172.792713
ODISHA                            204.629606
OUTSIDE-INDIA                     250.775789
PUDUCHERRY(UT)                    196.230637
PUNJAB                            228.662364
RAJASTHAN                         280.354518
SIKKIM                            179.342798
TAMIL NADU                        220.351702
TELANGANA                         222.757729
TRIPURA                           178.175363
UTTAR PRADESH                     192.716034
UTTARAKHAND                       216.313793
WEST BENGAL                       219.478585

In [60]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [61]:
df.groupby(['state','city','center_num']).agg({'Marks':['mean','count']}) # har city ka har state  ka marks ka mean and count nikale hai ya average marks

                                                             Marks
                                                              mean count
state                            city       center_num
ANDAMAN AND NICOBAR ISLANDS (UT) PORT BLAIR 110101      192.112798   461
                                            110102      192.594360   461
                                            110103      196.174757   103
ANDHRA PRADESH                   ANANTAPUR  121201      193.769316   906
                                            121202      207.425676   592
...                                                            ...   ...
WEST BENGAL                      SURI       461901      220.714660   764
                                            461902      225.723011   704
                                            461903      149.867012   579
                                            461904      151.131148   427
                                            461905      162.487437   199

[4750 rows x 2 columns]

In [62]:
df.groupby(['city','center_num']).agg({'Marks':['mean','count']})

                           Marks
                            mean count
city      center_num
ABU DHABI 990301      259.312608   579
ADILABAD  420901      190.109005   633
          420902      202.130350   514
          420903      175.142633   638
AGARTALA  430101      196.590508   906
...                          ...   ...
YAVATMAL  313407      171.421429   280
          313408      190.897436   234
          313409      171.177033   209
          313410      190.769953   213
          313411      165.135922   206

[4750 rows x 2 columns]

In [ ]:
df.groupby(['state','city',cen]).agg({'Marks':['mean','count']})

In [58]:
df.groupby(['state','city']).agg({'Marks':['mean']})

                                                         Marks
                                                          mean
state                            city
ANDAMAN AND NICOBAR ISLANDS (UT) PORT BLAIR         192.737561
ANDHRA PRADESH                   ANANTAPUR          197.060985
                                 BHIMAVARAM         199.756728
                                 CHIRALA            202.297830
                                 CHITTOOR           174.487047
...                                                        ...
WEST BENGAL                      NORTH 24 PARGANAS  226.512949
                                 PURBA MEDINIPUR    191.416456
                                 SILIGURI           216.213010
                                 SOUTH 24 PARGANAS  192.899645
                                 SURI               191.236813

[567 rows x 1 columns]

In [54]:
df.groupby('state').agg({'Marks':len})

                                   Marks
state
ANDAMAN AND NICOBAR ISLANDS (UT)    1025
ANDHRA PRADESH                     63846
ARUNACHAL PRADESH                   4774
ASSAM                              44273
BIHAR                             136193
CHANDIGARH(UT)                      3530
CHHATTISGARH                       44241
DADRA AND NAGAR HAVELI (UT)         1207
DAMAN AND DIU (UT)                   769
DELHI                              66090
GOA                                 4930
GUJARAT                            86952
HARYANA                            54864
HIMACHAL PRADESH                   19064
JAMMU AND KASHMIR                  47553
JHARKHAND                          34404
KARNATAKA                         150897
KERALA                            138546
LADAKH(UT)                           715
LAKSHADWEEP (UT)                     167
MADHYA PRADESH                    130238
MAHARASHTRA                       275245
MANIPUR                             8946
MEGHALAYA                           3757
MIZORAM                             2569
NAGALAND                            3705
ODISHA                             64318
OUTSIDE-INDIA                       4750
PUDUCHERRY(UT)                      5810
PUNJAB                             26573
RAJASTHAN                         193130
SIKKIM                              1444
TAMIL NADU                        153704
TELANGANA                          77892
TRIPURA                             5098
UTTAR PRADESH                     332631
UTTARAKHAND                        21989
WEST BENGAL                       117323

In [63]:
df.groupby(['state','city']).agg({'center_num':'nunique'})

                                                    center_num
state                            city
ANDAMAN AND NICOBAR ISLANDS (UT) PORT BLAIR                  3
ANDHRA PRADESH                   ANANTAPUR                   4
                                 BHIMAVARAM                  1
                                 CHIRALA                     1
                                 CHITTOOR                    3
...                                                        ...
WEST BENGAL                      NORTH 24 PARGANAS          12
                                 PURBA MEDINIPUR             7
                                 SILIGURI                   10
                                 SOUTH 24 PARGANAS          13
                                 SURI                        5

[567 rows x 1 columns]

In [7]:
df[["state","city"]]

                                    state        city
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

[2333162 rows x 2 columns]

In [8]:
df[["city","state","center_num"]]

               city                             state  center_num
0        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
1        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
2        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
3        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
4        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
...             ...                               ...         ...
2333157     KALYANI                       WEST BENGAL      461312
2333158     KALYANI                       WEST BENGAL      461312
2333159     KALYANI                       WEST BENGAL      461312
2333160     KALYANI                       WEST BENGAL      461312
2333161     KALYANI                       WEST BENGAL      461312

[2333162 rows x 3 columns]

In [9]:
df[['Marks', 'Srlno.', 'center_num', 'center_name', 'city', 'state']]

,Marks,Srlno.,center_num,center_name,city,state
0,46,1,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
1,226,2,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
2,449,3,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
3,424,4,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
4,222,5,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
...,...,...,...,...,...,...
2333157,279,135,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333158,102,136,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333159,14,137,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333160,179,138,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333161,91,139,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL

In [10]:
df.head()

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222

In [11]:
df.tail()

,state,city,center_name,center_num,Srlno.,Marks
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [12]:
df.iloc[0,5]

np.int64(46)

In [13]:
df.iloc[0,[3,5]]

center_num    110101
Marks             46
Name: 0, dtype: int64

In [14]:
df.iloc[[0,1],[1,2]]

         city               center_name
0  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
1  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1

In [15]:
df.iloc[[2,5,8],[5]]

   Marks
2    449
5    181
8     88

In [16]:
df.loc[[0,10,100,1000,10000],['state','city','Marks']]

                                  state        city  Marks
0      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     46
10     ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    322
100    ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR      5
1000   ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     73
10000                    ANDHRA PRADESH     NELLORE    458

In [17]:
df.loc[df['state'] == 'CHHATTISGARH']

,state,city,center_name,center_num,Srlno.,Marks
253641,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,1,58
253642,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,2,374
253643,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,3,98
253644,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,4,221
253645,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,5,512
...,...,...,...,...,...,...
297877,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,521,120
297878,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,522,392
297879,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,523,120
297880,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,524,361
297881,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,525,321

In [18]:
state = []

for i in df["state"]:
    if i not in state:
        state.append(i)
len(state)

38

In [19]:
city  = []

for i in df["city"]:
    if i not in  city:
        city.append(i)
len(city)

567

In [20]:
print(df.loc[df["city"] == "Mumbai"].shape) #ye bata raha hai ki kiya city mai mumbai bhi hai

(0, 6)

In [21]:
print(df.loc[df["state"] == "Chhattisgarh"].shape)   # ye bata raha hai  ki state mai chhattisgrah hai

(0, 6)

In [22]:
print(df["state"].unique()) # ye sab unique stae bata raha  hai

<StringArray>
['ANDAMAN AND NICOBAR ISLANDS (UT)',                   'ANDHRA PRADESH',
                'ARUNACHAL PRADESH',                            'ASSAM',
                            'BIHAR',                   'CHANDIGARH(UT)',
                     'CHHATTISGARH',      'DADRA AND NAGAR HAVELI (UT)',
               'DAMAN AND DIU (UT)',                            'DELHI',
                              'GOA',                          'GUJARAT',
                          'HARYANA',                 'HIMACHAL PRADESH',
                'JAMMU AND KASHMIR',                        'JHARKHAND',
                        'KARNATAKA',                           'KERALA',
                       'LADAKH(UT)',                 'LAKSHADWEEP (UT)',
                   'MADHYA PRADESH',                      'MAHARASHTRA',
                          'MANIPUR',                        'MEGHALAYA',
                          'MIZORAM',                         'NAGALAND',
                           'ODISHA',                    'OUTSIDE-INDIA',
                   'PUDUCHERRY(UT)',                           'PUNJAB',
                        'RAJASTHAN',                           'SIKKIM',
                       'TAMIL NADU',                        'TELANGANA',
                          'TRIPURA',                    'UTTAR PRADESH',
                      'UTTARAKHAND',                      'WEST BENGAL']
Length: 38, dtype: str

In [23]:
print(df["state"].nunique())   # ye sare number of unique value bata raha hai

38

In [24]:
print(df["city"].unique)    #ye sab unique city bat arahahi hamre dataset ka

<bound method Series.unique of 0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str>

In [25]:
print(df["city"].nunique) #  ye total numebr of unique value bata  rahah hai

<bound method IndexOpsMixin.nunique of 0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str>

In [26]:
cities = df.loc[df["state"] == "Chhattisgarh", "city"].unique()

print(len(cities))

0

In [27]:
print(df.loc[df["city"] == "Raipur", "center_name"].nunique())

0

In [28]:
df.loc[df["state"] == "CHHATTISGARH", "center_num"].nunique()

96

In [29]:
df.loc[df["state"] == "CHHATTISGARH", "city"].unique()

<StringArray>
['BHILAI NAGAR/DURG',     'BILASPUR (CG)',            'RAIPUR',
         'AMBIKAPUR',             'BALOD',           'BIJAPUR',
         'DANTEWADA',          'DHAMTARI',         'JAGDALPUR',
           'JANJGIR',            'KANKER',         'KONDAGAON',
             'KORBA',        'MAHASAMUND',        'NARAYANPUR',
           'RAIGARH',       'RAJNANDGAON',             'SUKMA',
      'MANENDRAGARH']
Length: 19, dtype: str

In [30]:
df.loc[df["city"] == "RAIPUR", "center_num"].nunique()

17

In [31]:
print(df.loc[df["state"] == "OUTSIDE-INDIA", "city"].unique())

<StringArray>
[ 'KUWAIT CITY',        'DUBAI',    'ABU DHABI',      'BANGKOK',
      'COLOMBO',         'DOHA',    'KATHMANDU', 'KUALA LUMPUR',
        'LAGOS',       'MANAMA',       'MUSCAT',       'RIYADH',
      'SHARJAH',    'SINGAPORE']
Length: 14, dtype: str

In [32]:
print(df.loc[df["state"] == "INDIA", "city"].unique())

<StringArray>
[]
Length: 0, dtype: str

In [33]:
print(df.loc[df["state"] != "OUTSIDE-INDIA"].shape)

(2328412, 6)

In [34]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [35]:
print(df.loc[df['Marks'] < 0, 'Marks'].count())

9477

In [36]:
print(df['Marks'].max())

720

In [37]:
df.loc[df['Marks'] == max(df['Marks'])].shape

(61, 6)

In [38]:
print(df.loc[df['Marks'] == max(df['Marks'])].shape)

(61, 6)

In [39]:
df.loc[(df['Marks'] >= 715) & (df['Marks'] <= 720)].shape

(288, 6)

In [40]:
counter = 0

for i in df['Marks']:
    if i >= 715 and i <= 720:
        counter = counter + 1

print(counter)

288

In [41]:
(df.loc[(df['Marks'] > 700) & (df['Marks'] < 720)].shape[0] / df.shape[0]) * 100

0.06746209650251461

In [42]:
#5. What percentage students scored between 700 to 720?
df.loc[(df['Marks'] < 100) | (df['Marks'] > 700)].shape[0]    # ye or ka symbol hai

695092

In [43]:
#7. How many students from Chhattisgarh scored between 700 and 720?
df.loc[(df['state'] == 'Chhattisgarh') & (df['Marks'] >= 700) & (df['Marks'] <= 720)].shape[0]

0

In [44]:
#8.How many students out of India scored between 700 and 720?
df.loc[(df['state'] != 'Chhattisgarh') & (df['Marks'] >= 700) & (df['Marks'] <= 720)].shape[0]

2321